id: Xpanse - Alert Handler
version: -1
name: Xpanse - Alert Handler
description: Default alert handling for Cortex Xpanse alerts.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 214bf91b-ba2c-4bc0-8f79-b8fa030361a1
    type: start
    task:
      id: 214bf91b-ba2c-4bc0-8f79-b8fa030361a1
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -80
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: ae2ce6f3-734a-47ff-84f6-61606557ffea
    type: playbook
    task:
      id: ae2ce6f3-734a-47ff-84f6-61606557ffea
      version: -1
      name: Xpanse - NMap - Detect Service
      description: Looks at what ASM sub-type the alert is and uses NMap to do a validation scan.
      type: playbook
      iscommand: false
      brand: ""
      playbookId: Xpanse - NMap - Detect Service
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      RemoteIP:
        complex:
          root: incident
          accessor: xpanseip
      RemotePort:
        complex:
          root: incident
          accessor: xpanseport
      ScanNumber:
        simple: "1"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: b216af93-2946-42a9-87b8-be99ddc48659
    type: title
    task:
      id: b216af93-2946-42a9-87b8-be99ddc48659
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 0a1ed7f5-fc19-4362-87c5-686806c40cbd
    type: playbook
    task:
      id: 0a1ed7f5-fc19-4362-87c5-686806c40cbd
      version: -1
      name: Xpanse - Alert Self-Enrichment
      description: Enrichment on the alert itself using Cortex Xpanse APIs.
      type: playbook
      iscommand: false
      brand: ""
      playbookId: Xpanse - Alert Self-Enrichment
    nexttasks:
      '#none#':
      - "4"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: eb478d2a-e73f-4840-8682-b02f063b587a
    type: playbook
    task:
      id: eb478d2a-e73f-4840-8682-b02f063b587a
      version: -1
      name: Xpanse - Alert Enrichment
      type: playbook
      iscommand: false
      brand: ""
      playbookId: Xpanse - Alert Enrichment
      description: ''
    nexttasks:
      '#none#':
      - "10"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 6f78d9b9-f90e-4c99-833d-742e6697d336
    type: title
    task:
      id: 6f78d9b9-f90e-4c99-833d-742e6697d336
      version: -1
      name: Is the service still exposed?
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 9d7740e1-a0b5-4fc5-8c01-e5e0b876bee4
    type: title
    task:
      id: 9d7740e1-a0b5-4fc5-8c01-e5e0b876bee4
      version: -1
      name: Asset and Alert Enrichment
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    continueonerrortype: ""
    form:
      description: Add one or multiple tags to the assets(s) associated with the current XSOAR incident.
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: What tag(s) do you want to add to asset(s)?
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: specificy what tags you want to add to the asset(s) associated to the current XSOAR incident in comma separated value format
        type: shortText
      sender: Your SOC team
      title: Determine tags to add to asset(s)
      totalanswers: 0
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc:
      body:
      cc:
      format: ""
      methods: []
      subject:
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b1d7833b-72f0-41b3-830e-898d61780676
      iscommand: false
      name: Determine tags to add to asset(s)
      type: collection
      version: -1
    taskid: b1d7833b-72f0-41b3-830e-898d61780676
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1020
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asm_id_list:
        complex:
          accessor: xpanseassetids
          root: incident
          transformers:
          - args:
              delimiter:
                value:
                  simple: ','
            operator: split
      tags:
        simple: ${Determine tags to add to asset(s).Answers.0}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex Xpanse
      description: Assigns tags to a list of assets.
      id: faa8b718-7e1b-4b27-8f50-7ceaac85553e
      iscommand: true
      name: Assign Tag to Asset(s)
      script: Cortex Xpanse|||asm-tag-asset-assign
      type: regular
      version: -1
    taskid: faa8b718-7e1b-4b27-8f50-7ceaac85553e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1180
        }
      }
  "10":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.WriteToExpanse
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determine whether playbook should write data back to Expanse.
      id: 975df226-fac6-4079-8cc3-66114bddd065
      iscommand: false
      name: Are we writing to Expanse?
      type: condition
      version: -1
    taskid: 975df226-fac6-4079-8cc3-66114bddd065
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 790
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "10_2_#default#": 0.9,
      "10_7_yes": 0.49
    },
    "paper": {
      "dimensions": {
        "height": 1515,
        "width": 380,
        "x": 450,
        "y": -80
      }
    }
  }
inputs:
- description: Write data back to Expanse? Default is False.
  key: WriteToXpanse
  playbookInputQuery:
  required: false
  value:
    simple: "False"
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.8.0
contentitemexportablefields:
  contentitemfields: {}
inputSections:
- description: Generic group for inputs
  inputs:
  - WriteToXpanse
  name: General (Inputs group)
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
