description: This playbook upgrades supported package on an AWS EC2 instance.
id: 'AWS - EC2 Package Upgrade'
inputSections:
- description: Generic group for inputs.
  inputs:
  - ASM Rule ID
  - Instance ID
  - Region
  - Assume Role
  name: General (Inputs group)
inputs:
- description: ASM rule ID.
  key: ASM Rule ID
  playbookInputQuery:
  required: true
  value:
    simple: ${alert.asmattacksurfaceruleid}
- description: Instance ID of the EC2.
  key: Instance ID
  playbookInputQuery:
  required: true
  value: {}
- description: AWS region of the EC2 instance.
  key: Region
  playbookInputQuery:
  required: true
  value: {}
- description: AWS role to be assumed.
  key: Assume Role
  playbookInputQuery:
  required: false
  value: {}
name: AWS - EC2 Package Upgrade
outputSections:
- description: Generic group for outputs.
  name: General (Outputs group)
  outputs:
  - remediatedFlag
outputs:
- contextPath: remediatedFlag
  description: Whether package is upgraded.
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a7db9bd9-d081-4e5a-8ec1-5597f2dbfd9e
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: a7db9bd9-d081-4e5a-8ec1-5597f2dbfd9e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.ASM Rule ID
          operator: isExists
          right:
            value: {}
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: AWS - System Manager
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: inputs.Instance ID
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: inputs.Region
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines if the AWS - Systems Manager integration instance is configured and input values are defined.
      id: 143d4a82-9911-415a-8eba-2be0767d93a0
      iscommand: false
      name: Is AWS - Systems Manager enabled and are Input values defined?
      type: condition
      version: -1
    taskid: 143d4a82-9911-415a-8eba-2be0767d93a0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 250
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9c47212d-dc9a-4e75-8c10-cebe121b9a86
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 9c47212d-dc9a-4e75-8c10-cebe121b9a86
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -120,
          "y": 2200
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asm_rule_id:
        simple: ${inputs.ASM Rule ID}
      assume_role:
        simple: ${inputs.Assume Role}
      instance_id:
        simple: ${inputs.Instance ID}
      region:
        simple: ${inputs.Region}
      version:
        simple: ${inputs.Version}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This is an AWS script that upgrades a package on the AWS EC2 instance.
      id: 6be26195-bb94-4dbe-8d57-65b5a2795a4d
      iscommand: false
      name: 'AWS EC2 Package Upgrade '
      script: AWSEC2PackageUpgrade
      type: regular
      version: -1
    taskid: 6be26195-bb94-4dbe-8d57-65b5a2795a4d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 800
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        simple: ${awsec2packageupgrade.run_command_id}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: command_id
      PollingCommandName:
        simple: aws-ssm-command-list
      Timeout:
        simple: "30"
      dt:
        simple: AWS.SSM.Command(val.Status !== 'Success').CommandId
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: d0bbf925-63cc-482e-8982-9b721af06623
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: d0bbf925-63cc-482e-8982-9b721af06623
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1290
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      command_id:
        simple: ${awsec2packageupgrade.run_command_id}
      roleArn:
        simple: ${inputs.Assume Role}
      roleSessionName:
        simple: AWS-SSM-Command
    separatecontext: false
    skipunavailable: false
    task:
      brand: AWS - System Manager
      description: Lists the commands requested by users of the Amazon Web Services account.
      id: 04e9d00d-0a88-4525-8b9e-89f65f858f3f
      iscommand: true
      name: Get status of command
      script: AWS - System Manager|||aws-ssm-command-list
      type: regular
      version: -1
    taskid: 04e9d00d-0a88-4525-8b9e-89f65f858f3f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1480
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.ASM Rule ID
          operator: inList
          right:
            value:
              simple: InsecureOpenSSH
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Does the provided ASM Rule ID exist in the list?
      id: ef75d92c-2289-4eb5-8252-b9610dea40c4
      iscommand: false
      name: Does this ASM Rule ID support AWS EC2 Patching?
      type: condition
      version: -1
    taskid: ef75d92c-2289-4eb5-8252-b9610dea40c4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 510
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${awsec2packageupgrade.run_command_flag}
          operator: isTrue
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the package upgrade command run is initiated via AWS SSM.
      id: b7d3aee8-7836-4104-8141-dbc0e67fab17
      iscommand: false
      name: AWS SSM Command Run Initiated?
      type: condition
      version: -1
    taskid: b7d3aee8-7836-4104-8141-dbc0e67fab17
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1010
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: remediatedFlag
      stringify:
        simple: "false"
      value:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: ce37dfb4-2343-454c-8b9f-359603b5cedb
      iscommand: false
      name: Set remediatedFlag to true
      script: Set
      type: regular
      version: -1
    taskid: ce37dfb4-2343-454c-8b9f-359603b5cedb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1970
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: remediatedFlag
      stringify:
        simple: "false"
      value:
        simple: "false"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 11283910-296e-4999-8415-0c0c6d9b42d5
      iscommand: false
      name: Set remediatedFlag to false
      script: Set
      type: regular
      version: -1
    taskid: 11283910-296e-4999-8415-0c0c6d9b42d5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -120,
          "y": 1970
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: AWS.SSM.Command.Status
          operator: isEqualString
          right:
            value:
              simple: Success
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Was the command run successful?
      id: 7e6574e6-6381-4b3b-8a69-5f69de432ae8
      iscommand: false
      name: AWS EC2 Package Upgrade success?
      type: condition
      version: -1
    taskid: 7e6574e6-6381-4b3b-8a69-5f69de432ae8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1670
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2215,
        "width": 950,
        "x": -120,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.10.0
