description: This playbook handles vulnerability issues by enriching assets to find potential remediation owners.
id: Cortex VM - Vulnerability Issue
inputs: []
name: Cortex VM - Vulnerability Issue
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5b7293b5-4b5f-4fa1-8fe8-54f93a4b1736
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 5b7293b5-4b5f-4fa1-8fe8-54f93a4b1736
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 440,
          "y": -310
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_id:
        simple: ${alert.asset_ids}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex Core - IR
      description: Get UAI asset info.
      id: eb2b56f7-6f9d-4e45-89f6-e35a6acf46fe
      iscommand: true
      name: core-get-asset-details
      script: Cortex Core - IR|||core-get-asset-details
      type: regular
      version: -1
    taskid: eb2b56f7-6f9d-4e45-89f6-e35a6acf46fe
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 140
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6d2b9017-6ca7-4d60-86f8-e64ea7481bf0
      iscommand: false
      name: Complete
      type: title
      version: -1
      description: ''
    taskid: 6d2b9017-6ca7-4d60-86f8-e64ea7481bf0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 900,
          "y": 2290
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 7b519123-1e10-4b1e-808b-85f627d1044a
      iscommand: false
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: 7b519123-1e10-4b1e-808b-85f627d1044a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": -180
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      text:
        simple: ${Core}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Extract all indicators according to server indicators configuration
      id: a3d0eeeb-33c7-4e60-8624-201282ff6039
      iscommand: true
      name: extractIndicators
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: a3d0eeeb-33c7-4e60-8624-201282ff6039
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 960
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      remediationowners:
        simple: '[]'
      vmassetowner:
        simple: '[]'
      vmassetownerunrankedraw:
        simple: '[]'
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Clear grid fields in case the playbook is rerun.
      id: 102c8b7f-38e1-44f0-80b8-dab00d206779
      iscommand: true
      name: Initialize grid fields
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: 102c8b7f-38e1-44f0-80b8-dab00d206779
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": -20
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      FQDN:
        complex:
          accessor: xdm__host__fqdn}
          root: ${Core.CoreAsset
          transformers:
          - args:
              applyIfEmpty: {}
              defaultValue:
                iscontext: true
                value:
                  simple: ${ExtractedIndicators.Domain}
            operator: SetIfEmpty
      HostName:
        simple: ${Core.CoreAsset.xdm__asset__name}${Core.CoreAsset.xdm__host__hostname}
      IPv4:
        complex:
          accessor: Platform Discovery}
          root: ${Core.CoreAsset.xdm__asset__normalized_fields
          transformers:
          - args:
              field:
                value:
                  simple: xdm.host.ipv4_addresses
            operator: getField
          - args:
              applyIfEmpty: {}
              defaultValue:
                value:
                  simple: ${ExtractedIndicators.IP}
            operator: SetIfEmpty
      IPv6:
        complex:
          accessor: Platform Discovery}
          root: ${Core.CoreAsset.xdm__asset__normalized_fields
          transformers:
          - args:
              field:
                value:
                  simple: xdm.host.ipv6_addresses
            operator: getField
          - args:
              applyIfEmpty:
                value:
                  simple: ${ExtractedIndicators.IPv6}
              defaultValue: {}
            operator: SetIfEmpty
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: 'Given provided indicators (IPs, Hostnames, FQDNs, etc), enriches ServiceNow CMDB information relevant to vulnerability issues.'
      id: 20c47529-2208-4cf7-8b19-decdeb9ae21a
      iscommand: false
      name: Cortex VM - ServiceNow CMDB
      playbookId: Cortex VM - ServiceNow CMDB
      type: playbook
      version: -1
    taskid: 20c47529-2208-4cf7-8b19-decdeb9ae21a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1120
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Core.CoreAsset
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if an asset was returned from the last command.
      id: 4658a7c4-0c63-4b3e-8606-2809121612b0
      iscommand: false
      name: Was an asset found?
      type: condition
      version: -1
    taskid: 4658a7c4-0c63-4b3e-8606-2809121612b0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 440,
          "y": 300
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: true
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      execution-timeout:
        simple: "3660"
      seconds:
        simple: "3600"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 4fad88cd-d0cf-4800-813e-e54f5591359a
      iscommand: false
      name: Sleep for 1 hour
      script: Sleep
      type: regular
      version: -1
    taskid: 4fad88cd-d0cf-4800-813e-e54f5591359a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": 470
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      asset_id:
        simple: ${alert.asset_ids}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex Core - IR
      description: Get UAI asset info.
      id: 4d193fad-296f-4231-87ae-10e30432ae65
      iscommand: true
      name: core-get-asset-details
      script: Cortex Core - IR|||core-get-asset-details
      type: regular
      version: -1
    taskid: 4d193fad-296f-4231-87ae-10e30432ae65
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": 630
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Core.CoreAsset
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if an asset was returned from the last command.
      id: e6375dd8-9e13-4e24-83f1-324edeb35817
      iscommand: false
      name: Was an asset found?
      type: condition
      version: -1
    taskid: e6375dd8-9e13-4e24-83f1-324edeb35817
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 840,
          "y": 790
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asmsystemids:
        simple: ${Core.CoreAsset.xdm__asset__name}
      ownerrelatedfield:
        simple: ${alert.vmassetowner}
      owners:
        simple: ${alert.vmassetownerunrankedraw}
      tenantcommand:
        simple: "True"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Recommend most likely service owners from those surfaced by Cortex ASM Enrichment.
      id: 2a91b474-457c-436d-8b55-d8b1314ae34e
      iscommand: false
      name: RankServiceOwners
      script: RankServiceOwners
      type: regular
      version: -1
    taskid: 2a91b474-457c-436d-8b55-d8b1314ae34e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1280
        }
      }
  "13":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: alert.vmassetowner
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "16"
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if an asset was returned from the last command.
      id: 85166537-1eaf-498a-892a-36158e5094ea
      iscommand: false
      name: Were remediation owner(s) found?
      type: condition
      version: -1
    taskid: 85166537-1eaf-498a-892a-36158e5094ea
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1445
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: temp_owners
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: alert.vmassetowner.email
              operator: isNotEqualString
              right:
                value:
                  simple: n/a
          root: alert.vmassetowner.email
          transformers:
          - operator: StringToArray
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 5347ba28-1141-44e6-87c5-b8a827ffd005
      iscommand: false
      name: Set temporary context (email)
      script: Set
      type: regular
      version: -1
    taskid: 5347ba28-1141-44e6-87c5-b8a827ffd005
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 660,
          "y": 1865
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: temp_owners
      value:
        complex:
          accessor: vmassetowner.name
          filters:
          - - left:
                iscontext: true
                value:
                  simple: alert.vmassetowner.email
              operator: isEqualString
              right:
                value:
                  simple: n/a
          root: alert
          transformers:
          - operator: StringToArray
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: f0418e37-2bbc-4e1f-81a9-9d7476c55253
      iscommand: false
      name: Set temporary context (name)
      script: Set
      type: regular
      version: -1
    taskid: f0418e37-2bbc-4e1f-81a9-9d7476c55253
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 230,
          "y": 1865
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: alert.vmassetowner.email
                    operator: isEqualString
                    right:
                      value:
                        simple: n/a
                root: alert.vmassetowner.email
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there an email that is n/a?
      id: 1ab0c461-9930-452e-87bd-ea89a72621b8
      iscommand: false
      name: Is there an email that is n/a?
      type: condition
      version: -1
    taskid: 1ab0c461-9930-452e-87bd-ea89a72621b8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 230,
          "y": 1680
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: alert.vmassetowner.email
                    operator: isNotEqualString
                    right:
                      value:
                        simple: n/a
                root: alert.vmassetowner.email
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there an email that is not n/a?
      id: cfd67951-a38a-48f3-8aa6-b6f1e667293e
      iscommand: false
      name: Is there an email that is not n/a?
      type: condition
      version: -1
    taskid: cfd67951-a38a-48f3-8aa6-b6f1e667293e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 660,
          "y": 1680
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      remediationowners:
        simple: ${temp_owners}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 00c9ce0c-6f90-4183-8f20-56751597a3e4
      iscommand: true
      name: Set remediation owners field
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: 00c9ce0c-6f90-4183-8f20-56751597a3e4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 2120
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "11_2_#default#": 0.44,
      "11_4_yes": 0.42,
      "8_4_yes": 0.21
    },
    "paper": {
      "dimensions": {
        "height": 2665,
        "width": 1050,
        "x": 230,
        "y": -310
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.10.0
