id: 'Cortex VM - Vulnerability Issue'
inputs: []
name: Cortex VM - Vulnerability Issue
outputs: []
sourceplaybookid: 'uvem-main'
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 353c32e7-e317-421d-8cc0-6b8538a598e8
      iscommand: false
      name: ""
      version: -1
    taskid: 353c32e7-e317-421d-8cc0-6b8538a598e8
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 440,
          "y": -150
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_id:
        simple: ${alert.asset_ids}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex Core - IR
      description: Get UAI asset info
      id: a06b0a87-b0cb-4908-8da3-3f98fcd04a03
      iscommand: true
      name: core-get-asset-details
      script: Cortex Core - IR|||core-get-asset-details
      type: regular
      version: -1
    taskid: a06b0a87-b0cb-4908-8da3-3f98fcd04a03
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 160
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dc4e654e-106d-40b8-8bb7-d18ecf433aa8
      iscommand: false
      name: Complete
      type: title
      version: -1
    taskid: dc4e654e-106d-40b8-8bb7-d18ecf433aa8
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1650
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: f585ae47-07fb-4fcf-8641-a38b4580c96b
      iscommand: false
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: f585ae47-07fb-4fcf-8641-a38b4580c96b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 240,
          "y": -10
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      text:
        simple: ${Core}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Extract all indicators according to server indicators configuration
      id: b2a7bbc6-b509-425e-8e00-d7887cec69fd
      iscommand: true
      name: extractIndicators
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: b2a7bbc6-b509-425e-8e00-d7887cec69fd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 990
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      asmserviceowner:
        simple: '[]'
      asmserviceownerunrankedraw:
        simple: '[]'
      vmassetownerunrankedraw:
        simple: '[]'
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Clear ASM grid fields in case the playbook is rerun.
      id: dec52f51-5fa8-4fd7-8dd5-493149191fc5
      iscommand: true
      name: Initialize grid fields - TO UPDATE
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: dec52f51-5fa8-4fd7-8dd5-493149191fc5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 650,
          "y": -10
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      HostName:
        simple: ${Core.CoreAsset.xdm__asset__name}
      IPv4:
        simple: ${ExtractedIndicators.IP}
      IPv6:
        simple: ${ExtractedIndicators.IPv6}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: 'TODO Edit Given the IP address this playbook enriches ServiceNow
        CMDB information relevant to ASM alerts. '
      id: 84c69e8e-c437-4f16-8988-62eccd98977c
      iscommand: false
      name: Cortex VM - ServiceNow CMDB - FIGURE OUT IPV6
      playbookId: 'Cortex VM - ServiceNow CMDB'
      type: playbook
      version: -1
    taskid: 84c69e8e-c437-4f16-8988-62eccd98977c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1150
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Core.CoreAsset
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 67f2a6dd-6753-42d3-8a87-dead3a9c0965
      iscommand: false
      name: Was an asset found?
      type: condition
      version: -1
    taskid: 67f2a6dd-6753-42d3-8a87-dead3a9c0965
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 440,
          "y": 330
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: true
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      execution-timeout:
        simple: "3660"
      seconds:
        simple: "3600"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 9d9290fd-40ab-4843-84bb-cdcc768a5917
      iscommand: false
      name: Sleep for 1 hour
      script: Sleep
      type: regular
      version: -1
    taskid: 9d9290fd-40ab-4843-84bb-cdcc768a5917
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 850,
          "y": 500
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      asset_id:
        simple: ${alert.asset_ids}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex Core - IR
      description: Get UAI asset info
      id: 06bf2979-ce41-42ba-8afb-297c71762403
      iscommand: true
      name: core-get-asset-details
      script: Cortex Core - IR|||core-get-asset-details
      type: regular
      version: -1
    taskid: 06bf2979-ce41-42ba-8afb-297c71762403
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 850,
          "y": 660
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Core.CoreAsset
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 127036eb-a5d5-42a3-842c-e6dc8d0ab071
      iscommand: false
      name: Was an asset found?
      type: condition
      version: -1
    taskid: 127036eb-a5d5-42a3-842c-e6dc8d0ab071
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 850,
          "y": 820
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asmsystemids:
        simple: ${Core.CoreAsset.xdm__asset__name}
      owners:
        simple: ${alert.vmassetownerunrankedraw}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Recommend most likely service owners from those surfaced by Cortex
        ASM Enrichment.
      id: 19c20899-187c-4eac-82e8-e96cc2082217
      iscommand: false
      name: RankServiceOwners
      script: RankServiceOwners
      type: regular
      version: -1
    taskid: 19c20899-187c-4eac-82e8-e96cc2082217
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1330
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1865,
        "width": 990,
        "x": 240,
        "y": -150
      }
    }
  }
