id: Cortex ASM - On Prem Remediation_EXPANDR-5997
version: 1
contentitemexportablefields:
  contentitemfields:
    packID: ''
    packName: Cortex Attack Surface Management
    itemVersion: 1.7.0
    fromServerVersion: 6.8.0
    toServerVersion: ''
    definitionid: ''
    prevname: ''
vcShouldKeepItemLegacyProdMachine: false
name: Cortex ASM - On Prem Remediation_EXPANDR-5997
description: "This playbook adds new block rule(s) to on-prem firewall vendors in order to block internet access for internet exposures.\n\nConditions:\nThis is currently limited to stand-alone firewalls for PAN-OS."
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: 5ed11d73-b0ea-4835-8b0c-bd100d1d6afc
    type: start
    task:
      id: 5ed11d73-b0ea-4835-8b0c-bd100d1d6afc
      version: -1
      name: ''
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '5'
    separatecontext: false
    continueonerrortype: ''
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": -460\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '1':
    id: '1'
    taskid: 0a99ebf4-33d5-4de3-8258-bfa867d8e42d
    type: regular
    task:
      id: 0a99ebf4-33d5-4de3-8258-bfa867d8e42d
      version: -1
      name: pan-os-list-rules
      description: Returns a list of predefined Security Rules. (When passing a query, all other arguments are overridden. Make sure the query includes all the filters you want).
      script: Panorama|||pan-os-list-rules
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      rulename:
        complex:
          root: inputs.RuleName
    separatecontext: false
    continueonerrortype: ''
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": -140\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '2':
    id: '2'
    taskid: c5934c1a-189d-4391-87a3-bd398488bfdd
    type: playbook
    task:
      id: c5934c1a-189d-4391-87a3-bd398488bfdd
      version: -1
      name: PAN-OS - Block Destination Service_EXPANDR-5997
      description: 'This playbook blocks a destination IP and service (TCP or UDP port) by creating a rule for a specific device group on PAN-OS. '
      playbookName: PAN-OS - Block Destination Service_EXPANDR-5997
      type: playbook
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      AutoCommit:
        simple: 'True'
      DestinationZone:
        complex:
          root: Panorama.SecurityRule
          accessor: To
      DeviceGroup:
        complex:
          root: inputs.DeviceGroup
      IP:
        complex:
          root: inputs.RemoteIP
      LogForwarding:
        complex:
          root: Panorama.SecurityRule
          accessor: LogForwardingProfile
      ObjectNamePrefix:
        simple: xpanse-ar-object-
      Port:
        complex:
          root: inputs.RemotePort
          transformers:
          - operator: Stringify
      Protocol:
        complex:
          root: inputs.RemoteProtocol
      RuleNamePrefix:
        simple: xpanse-ar-rule
      ServiceNamePrefix:
        simple: xpanse-ar-service-
      SourceZone:
        complex:
          root: Panorama.SecurityRule
          accessor: From
      WhereRule:
        simple: top
    separatecontext: true
    continueonerrortype: ''
    loop:
      iscommand: false
      exitCondition: ''
      wait: 1
      max: 100
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": 250\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '4':
    id: '4'
    taskid: 3a635a5c-f1e5-4d7f-8dbb-0cb0e5ab0907
    type: title
    task:
      id: 3a635a5c-f1e5-4d7f-8dbb-0cb0e5ab0907
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ''
    separatecontext: false
    continueonerrortype: ''
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": 420\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '5':
    id: '5'
    taskid: fd882842-1e2d-4a8e-87ec-a5c9d94a7614
    type: condition
    task:
      id: fd882842-1e2d-4a8e-87ec-a5c9d94a7614
      version: -1
      name: Is DeviceGroup specified?
      description: Checks if DeviceGroup input is specified because of different !pan-os-list-rule commands for standalone firewall vs Panorama.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      '#default#':
      - '1'
      yes:
      - '6'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: inputs.DeviceGroup
            iscontext: true
    continueonerrortype: ''
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": -340\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '6':
    id: '6'
    taskid: 5abb12f9-f509-4f57-8550-b278b83bd784
    type: regular
    task:
      id: 5abb12f9-f509-4f57-8550-b278b83bd784
      version: -1
      name: pan-os-list-rules (pre-rulebase)
      description: Returns a list of predefined Security Rules. (When passing a query, all other arguments are overridden. Make sure the query includes all the filters you want).
      script: Panorama|||pan-os-list-rules
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#error#':
      - '7'
      '#none#':
      - '2'
    scriptarguments:
      device-group:
        complex:
          root: inputs.DeviceGroup
      pre_post:
        simple: pre-rulebase
      rulename:
        complex:
          root: inputs.RuleName
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: "{\n  \"position\": {\n    \"x\": 890,\n    \"y\": -140\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '7':
    id: '7'
    taskid: 615b0867-29da-43b6-860e-b05c01ce379c
    type: regular
    task:
      id: 615b0867-29da-43b6-860e-b05c01ce379c
      version: -1
      name: pan-os-list-rules (post-rulebase)
      description: Returns a list of predefined Security Rules. (When passing a query, all other arguments are overridden. Make sure the query includes all the filters you want).
      script: Panorama|||pan-os-list-rules
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      device-group:
        complex:
          root: inputs.DeviceGroup
      pre_post:
        simple: post-rulebase
      rulename:
        complex:
          root: inputs.RuleName
    separatecontext: false
    continueonerrortype: ''
    view: "{\n  \"position\": {\n    \"x\": 890,\n    \"y\": 70\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n      \"height\": 945,\n      \"width\": 810,\n      \"x\": 460,\n      \"y\": -460\n    }\n  }\n}"
inputs:
- key: RuleName
  value: {}
  required: true
  description: Firewall rule name to look up in the company configuration setting for block rule.
  playbookInputQuery:
- key: RemoteIP
  value:
    complex:
      root: alert
      accessor: remoteip
  required: true
  description: IP address of the service.
  playbookInputQuery:
- key: RemoteProtocol
  value:
    complex:
      root: alert
      accessor: appid
  required: true
  description: Protocol of the service.
  playbookInputQuery:
- key: RemotePort
  value:
    complex:
      root: alert
      accessor: remoteport
  required: true
  description: Port number of the service.
  playbookInputQuery:
- key: DeviceGroup
  value: {}
  required: false
  description: Device Group of the firewall rule to lookup
  playbookInputQuery:
outputs: []
sourceplaybookid: Cortex ASM - On Prem Remediation
