description: Playbook to enriches Service owner in Azure directory.
id: Cortex ASM - Active Directory Enrichment
inputs:
- description: The service owner to enrich in Azure directory.
  key: serviceowner
  playbookInputQuery:
  required: false
  value: {}
name: Cortex ASM - Active Directory Enrichment
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4437618c-1c1c-4422-8257-18f7289ac293
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 4437618c-1c1c-4422-8257-18f7289ac293
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0c488bd1-1686-4a20-87e8-2f87fab49b68
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 0c488bd1-1686-4a20-87e8-2f87fab49b68
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 40,
          "y": 1150
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      properties:
        simple: displayName
      user:
        simple: ${inputs.serviceowner}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Microsoft Graph User
      description: "Retrieves the properties and relationships for Global Admins. \n\nFor more information, visit: https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0. \nPermissions: - User.Read (Delegated) - User.Read.All (Application)"
      id: 70e25786-8973-4ba9-81f2-cb67bebc3272
      iscommand: true
      name: Lookup user details in Active Directory.
      script: Microsoft Graph User|||msgraph-user-get
      type: regular
      version: -1
    taskid: 70e25786-8973-4ba9-81f2-cb67bebc3272
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 370
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Microsoft Graph User
                root: modules
          operator: isExists
          right:
            value: {}
      - - left:
            iscontext: true
            value:
              simple: inputs.serviceowner
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines if the Microsoft Graph User integration instance is configured.
      id: b21e2b1d-6220-47d6-81a2-fdb941916747
      iscommand: false
      name: Is Microsoft Graph User enabled and Input defined?
      type: condition
      version: -1
    taskid: b21e2b1d-6220-47d6-81a2-fdb941916747
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f16dc8b2-5f06-4194-8ad0-715d6cb4151c
      iscommand: false
      name: Set Fields
      type: title
      version: -1
      description: ''
    taskid: f16dc8b2-5f06-4194-8ad0-715d6cb4151c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 500,
          "y": 535
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      gridfield:
        simple: asmserviceownerunrankedraw
      keys:
        simple: name,email,source,timestamp
      val1:
        simple: ${MSGraphUser.DisplayName}
      val2:
        simple: ${MSGraphUser.Mail}
      val3:
        simple: Active-Directory
      val4:
        simple: TIMESTAMP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the potential Azure service owner to the grid field for the ASM service owner object.
      id: 292dde13-00de-4af0-8b54-fca675a03fb7
      iscommand: false
      name: Set service owner grid field
      script: GridFieldSetup
      type: regular
      version: -1
    taskid: 292dde13-00de-4af0-8b54-fca675a03fb7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 280,
          "y": 950
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: MSGraphUser.DisplayName
          operator: isNotEmpty
        - left:
            iscontext: true
            value:
              simple: MSGraphUser.DisplayName
          operator: isNotEqualString
          right:
            value:
              simple: "null"
      - - left:
            iscontext: true
            value:
              simple: MSGraphUser.Mail
          operator: isNotEmpty
        - left:
            iscontext: true
            value:
              simple: MSGraphUser.Mail
          operator: isNotEqualString
          right:
            value:
              simple: "null"
      label: Set Name and Mail
    - condition:
      - - left:
            iscontext: true
            value:
              simple: MSGraphUser.DisplayName
          operator: isNotEqualString
          right:
            value:
              simple: "null"
        - left:
            iscontext: true
            value:
              simple: MSGraphUser.DisplayName
          operator: isNotEmpty
      label: Set Name
    - condition:
      - - left:
            iscontext: true
            value:
              simple: MSGraphUser.Mail
          operator: isNotEqualString
          right:
            value:
              simple: "null"
        - left:
            iscontext: true
            value:
              simple: MSGraphUser.Mail
          operator: isNotEmpty
      label: Set Mail
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      Set Mail:
      - "16"
      Set Name:
      - "15"
      Set Name and Mail:
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Ownership information exists?
      id: 944b74fd-3b3b-4cd4-8b1a-f2ea2a5d4e54
      iscommand: false
      name: Ownership information exists?
      type: condition
      version: -1
    taskid: 944b74fd-3b3b-4cd4-8b1a-f2ea2a5d4e54
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": 680
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      gridfield:
        simple: asmserviceownerunrankedraw
      keys:
        simple: name,email,source,timestamp
      val1:
        simple: ${MSGraphUser.DisplayName}
      val2:
        simple: n/a
      val3:
        simple: Active-Directory
      val4:
        simple: TIMESTAMP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the potential Azure service owner to the grid field for the ASM service owner object.
      id: 330aedad-c9dd-4084-856d-963196a34127
      iscommand: false
      name: Set service owner grid field
      script: GridFieldSetup
      type: regular
      version: -1
    taskid: 330aedad-c9dd-4084-856d-963196a34127
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 720,
          "y": 950
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      gridfield:
        simple: asmserviceownerunrankedraw
      keys:
        simple: name,email,source,timestamp
      val1:
        simple: n/a
      val2:
        simple: ${MSGraphUser.Mail}
      val3:
        simple: Active-Directory
      val4:
        simple: TIMESTAMP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the potential Azure service owner to the grid field for the ASM service owner object.
      id: 029d0ddf-20db-4d0b-8ea6-f12d902564ae
      iscommand: false
      name: Set service owner grid field
      script: GridFieldSetup
      type: regular
      version: -1
    taskid: 029d0ddf-20db-4d0b-8ea6-f12d902564ae
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1180,
          "y": 950
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1165,
        "width": 1520,
        "x": 40,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.10.0
