id: Cortex ASM - Remediation
version: -1
name: Cortex ASM - Remediation
description: This playbook contains all the cloud provider sub playbooks for remediation.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0ec0ccf5-ca95-46cc-8cad-2fcff1f458c7
    type: start
    task:
      id: 0ec0ccf5-ca95-46cc-8cad-2fcff1f458c7
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: f026b4a7-f96f-4870-86c8-09ea5b524218
    type: condition
    task:
      id: f026b4a7-f96f-4870-86c8-09ea5b524218
      version: -1
      name: What provider is this service?
      description: Determines which cloud provider the service is in order to direct to the correct enrichment.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      AWS:
      - "10"
      GCP:
      - "9"
      Azure:
      - "6"
      Unclaimed S3 Bucket:
      - "7"
      On Prem:
      - '12'
    separatecontext: false
    conditions:
    - label: AWS
      condition:
      - - operator: containsGeneral
          left:
            value:
              complex:
                root: alert.asmcloud
                accessor: provider
            iscontext: true
          right:
            value:
              simple: AWS
    - label: GCP
      condition:
      - - operator: containsGeneral
          left:
            value:
              complex:
                root: alert.asmcloud
                accessor: provider
            iscontext: true
          right:
            value:
              simple: GCP
    - label: Azure
      condition:
      - - operator: containsGeneral
          left:
            value:
              complex:
                root: alert.asmcloud
                accessor: provider
            iscontext: true
          right:
            value:
              simple: Azure
    - label: Unclaimed S3 Bucket
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: alert
                accessor: asmattacksurfaceruleid
                transformers:
                - operator: StripChars
                  args:
                    chars:
                      value:
                        simple: '[\"]'
            iscontext: true
          right:
            value:
              simple: UnclaimedS3Bucket
    - label: On Prem
      condition:
      - - operator: containsGeneral
          left:
            value:
              complex:
                root: alert.asmcloud
                accessor: provider
            iscontext: true
          right:
            value:
              simple: On Prem
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 235
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 857fd027-e074-4bf2-825e-cbd22c4a5beb
    type: title
    task:
      id: 857fd027-e074-4bf2-825e-cbd22c4a5beb
      version: -1
      name: Completed
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 860
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 51fddee6-a8a3-4e97-8783-b061d8ecfd00
    type: playbook
    task:
      id: 51fddee6-a8a3-4e97-8783-b061d8ecfd00
      version: -1
      name: Azure - Network Security Group Remediation
      description: |-
        This playbook adds new Azure Network Security Groups (NSG) rules to NSGs attached to a NIC. The new rules will give access only to a private IP address range and block traffic that's exposed to the public internet ([using the private IP of the VM as stated in Azure documentation](https://learn.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview)). For example, if RDP is exposed to the public internet, this playbook adds new firewall rules that only allows traffic from private IP address and blocks the rest of the RDP traffic.

        Conditions and limitations:
        - Limited to one resource group.
        - 200 Azure rules viewed at once to find the offending rule.
        - 2 priorities lower than the offending rule priority must be available.
        - Adds rules to NSGs associated to NICs.
      playbookName: Azure - Network Security Group Remediation
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      AzureSecurityGroup:
        complex:
          root: alert.asmsystemids
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: alert.asmsystemids.type
                iscontext: true
              right:
                value:
                  simple: ASSET-SG
          accessor: id
      AzureVMPrivateIP:
        complex:
          root: alert.asmprivateip
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: alert.asmprivateip.source
                iscontext: true
              right:
                value:
                  simple: Azure
          transformers:
          - operator: getField
            args:
              field:
                value:
                  simple: IP
      RemotePort:
        complex:
          root: alert
          accessor: remoteport
      RemoteProtocol:
        complex:
          root: alert
          accessor: protocol
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 1100,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: eefc9a4f-11f6-4dd3-837e-c000f7f2d7ac
    type: playbook
    task:
      id: eefc9a4f-11f6-4dd3-837e-c000f7f2d7ac
      version: -1
      name: AWS - Unclaimed S3 Bucket Remediation
      description: The playbook will create the unclaimed S3 bucket.
      playbookName: AWS - Unclaimed S3 Bucket Remediation
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      S3BucketName:
        complex:
          root: alert.asmsystemids
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: alert.asmsystemids.type
                iscontext: true
              right:
                value:
                  simple: S3-BucketName
          accessor: id
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 220,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: e3f88892-eff3-4e72-857a-f24e290f71f4
    type: playbook
    task:
      id: e3f88892-eff3-4e72-857a-f24e290f71f4
      version: -1
      name: AWS - Security Group Remediation v2
      description: This playbook takes in some information about an EC2 instance (ID and public_ip) and with provided port and protocol, determines what security groups on the primary interface of an EC2 instance are over-permissive.  It uses an automation to determine what interface on an EC2 instance has an over-permissive security group on, determine which security groups have over-permissive rules and to replace them with a copy of the security group that has only the over-permissive portion removed.  Over-permissive is defined as sensitive ports (SSH, RDP, etc) being exposed to the internet via IPv4.
      playbookName: AWS - Security Group Remediation v2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      InstanceID:
        complex:
          root: alert.asmsystemids
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: alert.asmsystemids.type
                iscontext: true
              right:
                value:
                  simple: ASSET-ID
          accessor: id
      Port:
        complex:
          root: alert
          accessor: remoteport
      Protocol:
        complex:
          root: alert
          accessor: protocol
          transformers:
          - operator: toLowerCase
      PublicIP:
        complex:
          root: alert
          accessor: remoteip
      Region:
        complex:
          root: alert.asmcloud
          accessor: region
          transformers:
          - operator: FirstArrayElement
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: "{\n  \"position\": {\n    \"x\": -30,\n    \"y\": 680\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 70238dbb-d732-45c0-8bbc-8454b2a54279
    type: playbook
    task:
      id: 70238dbb-d732-45c0-8bbc-8454b2a54279
      version: -1
      name: GCP - Firewall Remediation
      playbookName: GCP - Firewall Remediation
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      GcpInstance:
        complex:
          root: alert.asmsystemids
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: alert.asmsystemids.type
                iscontext: true
              right:
                value:
                  simple: ASSET-NAME
          accessor: id
      GcpNetwork:
        complex:
          root: alert.asmsystemids
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: alert.asmsystemids.type
                iscontext: true
              right:
                value:
                  simple: ASSET-VIRTUAL-NET
          accessor: id
      GcpProject:
        complex:
          root: alert.asmcloud
          accessor: project
          transformers:
          - operator: FirstArrayElement
      GcpZone:
        complex:
          root: alert.asmsystemids
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: alert.asmsystemids.type
                iscontext: true
              right:
                value:
                  simple: ASSET-ZONE
          accessor: id
      RemotePort:
        complex:
          root: alert
          accessor: remoteport
      RemoteProtocol:
        complex:
          root: alert
          accessor: protocol
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 680,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 6d374aa1-59cd-485c-8fc9-6ee5fdd7867a
    type: condition
    task:
      id: 6d374aa1-59cd-485c-8fc9-6ee5fdd7867a
      version: -1
      name: Is AWSAssumeRoleName Input defined?
      description: Determines which cloud provider the service is in order to direct to the correct enrichment.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: inputs.AWSAssumeRoleName
            iscontext: true
    continueonerrortype: ""
    view: "{\n  \"position\": {\n    \"x\": -210,\n    \"y\": 450\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 8447163f-46f0-4567-8871-d38e950991f3
    type: playbook
    task:
      id: 8447163f-46f0-4567-8871-d38e950991f3
      version: -1
      name: AWS - Security Group Remediation v2
      description: This playbook takes in some information about an EC2 instance (ID and public_ip) and with provided port and protocol, determines what security groups on the primary interface of an EC2 instance are over-permissive.  It uses an automation to determine what interface on an EC2 instance has an over-permissive security group on, determine which security groups have over-permissive rules and to replace them with a copy of the security group that has only the over-permissive portion removed.  Over-permissive is defined as sensitive ports (SSH, RDP, etc) being exposed to the internet via IPv4.
      playbookName: AWS - Security Group Remediation v2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      AWSAssumeArn:
        complex:
          root: alert.asmcloud
          accessor: project
          transformers:
          - operator: FirstArrayElement
          - operator: concat
            args:
              prefix:
                value:
                  simple: 'arn:aws:iam::'
              suffix:
                value:
                  simple: :role/
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: inputs.AWSAssumeRoleName
                iscontext: true
      InstanceID:
        complex:
          root: alert.asmsystemids
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: alert.asmsystemids.type
                iscontext: true
              right:
                value:
                  simple: ASSET-ID
          accessor: id
      Port:
        complex:
          root: alert
          accessor: remoteport
      Protocol:
        complex:
          root: alert
          accessor: protocol
          transformers:
          - operator: toLowerCase
      PublicIP:
        complex:
          root: alert
          accessor: remoteip
      Region:
        complex:
          root: alert.asmcloud
          accessor: region
          transformers:
          - operator: FirstArrayElement
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: "{\n  \"position\": {\n    \"x\": -460,\n    \"y\": 680\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '12':
    id: '12'
    taskid: a016d354-84fc-4c97-880d-3f2c93d43aaf
    type: playbook
    task:
      id: a016d354-84fc-4c97-880d-3f2c93d43aaf
      version: -1
      name: Cortex ASM - On Prem Remediation
      playbookName: Cortex ASM - On Prem Remediation
      type: playbook
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      RemoteIP:
        complex:
          root: alert
          accessor: remoteip
      RemotePort:
        complex:
          root: alert
          accessor: remoteport
      RemoteProtocol:
        complex:
          root: alert
          accessor: protocol
          transformers:
          - operator: toLowerCase
      RuleName:
        complex:
          root: alert.asmsystemids
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: alert.asmsystemids.type
                iscontext: true
              right:
                value:
                  simple: FIREWALL-RULE-NAME
          accessor: id
    separatecontext: true
    continueonerrortype: ''
    loop:
      iscommand: false
      exitCondition: ''
      wait: 1
      max: 100
    view: "{\n  \"position\": {\n    \"x\": 1520,\n    \"y\": 420\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n      \"height\": 875,\n      \"width\": 2360,\n      \"x\": -460,\n      \"y\": 50\n    }\n  }\n}"
inputs:
- key: AWSAssumeRoleName
  value: {}
  required: false
  description: If assuming roles for AWS, this is the name of the role to assume (should be the same for all organizations)
  playbookInputQuery:
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.5.0
