description: Identifies and recommends the most likely owners of the service, additionally
  citing an explanation and ranking score for each.
dirtyInputs: true
id: Cortex ASM - Service Ownership
inputs: []
name: Cortex ASM - Service Ownership
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      id: b8b84a8c-31ee-4daa-884a-5c8fae07434e
      iscommand: false
      name: ""
      version: -1
    taskid: b8b84a8c-31ee-4daa-884a-5c8fae07434e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": -50,
          "y": -150
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asmsystemids:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: alert.asmsystemids.type
              operator: containsString
              right:
                value:
                  simple: ASSET-NAME
          root: alert.asmsystemids
          transformers:
          - args:
              field:
                value:
                  simple: id
            operator: getField
      owners:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: alert.asmserviceownerunrankedraw.accounttype
              operator: isNotExists
            - left:
                iscontext: true
                value:
                  simple: alert.asmserviceownerunrankedraw.accounttype
              operator: isNotEqualString
              right:
                value:
                  simple: SERVICE-ACCOUNT
          root: alert.asmserviceownerunrankedraw
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Recommend most likely service owners from those surfaced by Cortex
        ASM Enrichment.
      id: 36f91bcf-47d2-403f-8036-6371edfdab2a
      iscommand: false
      name: Normalize and rank likely service owners
      script: RankServiceOwners
      type: regular
      version: -1
    taskid: 36f91bcf-47d2-403f-8036-6371edfdab2a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -50,
          "y": 1000
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: alert.asmserviceownerunrankedraw
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: alert.asmserviceownerunrankedraw.email
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: alert.asmserviceownerunrankedraw.name
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: alert.asmserviceownerunrankedraw.source
          operator: isNotEmpty
      label: unranked raw
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      unranked raw:
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines if the asmserviceowner or asmserviceownerunrankedraw
        fields have been populated to continue.
      id: fc631aab-e26a-46ec-823f-8c32ea5d2b7a
      iscommand: false
      name: Is asmserviceownerunrankedraw populated?
      type: condition
      version: -1
    taskid: fc631aab-e26a-46ec-823f-8c32ea5d2b7a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -50,
          "y": 0
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f0be60f7-946b-484c-8f3f-2fce48393887
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f0be60f7-946b-484c-8f3f-2fce48393887
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 190,
          "y": 1170
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ASM.ExternalService
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines if there was a result from the previous command to continue
        cloud enrichment.
      id: 9cc9f303-da36-400b-83ed-f1bb106cbe04
      iscommand: false
      name: Was there a result?
      type: condition
      version: -1
    taskid: 9cc9f303-da36-400b-83ed-f1bb106cbe04
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -50,
          "y": 640
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      service_id:
        complex:
          accessor: asmserviceid
          root: alert
          transformers:
          - args:
              chars:
                value:
                  simple: '[\"]'
            operator: StripChars
    separatecontext: false
    skipunavailable: true
    task:
      brand: Cortex Attack Surface Management
      description: Get service details according to the service ID.
      id: a1bbef47-dfa9-4e51-8be1-4d0d1d70c470
      iscommand: true
      name: Get external service information
      script: Cortex Attack Surface Management|||asm-get-external-service
      type: regular
      version: -1
    taskid: a1bbef47-dfa9-4e51-8be1-4d0d1d70c470
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -50,
          "y": 480
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Cortex Attack Surface Management
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines if the "Cortex Attack Surface Management" integration
        instance is configured to continue with cloud enrichment.
      id: 62302e49-c1c0-4c9d-8dff-d32b1502daf2
      iscommand: false
      name: Is Cortex ASM enabled?
      type: condition
      version: -1
    taskid: 62302e49-c1c0-4c9d-8dff-d32b1502daf2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -50,
          "y": 200
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      external_service:
        complex:
          root: ASM.ExternalService.externally_detected_providers
      owners:
        simple: ${alert.asmserviceownerunrankedraw}
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Parse a GCP service account email for the project name, then lookup
        project owners and add them to a list of potential service owners for ranking.
      id: d99dfe0a-1433-4c4f-8bc3-44bb2c53c3f1
      iscommand: false
      name: Look up project owners for service account
      script: GetProjectOwners
      type: regular
      version: -1
    taskid: d99dfe0a-1433-4c4f-8bc3-44bb2c53c3f1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -50,
          "y": 825
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "15_19_yes": 0.36,
      "17_10_#default#": 0.2,
      "9_10_#default#": 0.33
    },
    "paper": {
      "dimensions": {
        "height": 1385,
        "width": 620,
        "x": -50,
        "y": -150
      }
    }
  }
